version: '3'
services:
  web:
    build: ./
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    ports:
     - "5000:5000"

  neo4j:
    image: neo4j:3.2.5
    ports:
     - "17474:7474"
    volumes:
     - ./db/dbms:/data/dbms

volumes:
  neo4j: